# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bJFq8wq1gQ9D4hVK1haXFzInNejwBW5x
"""

!pip install alpha_vantage pandas

from alpha_vantage.foreignexchange import ForeignExchange
import pandas as pd

# Alpha VantageのAPIキーを入力
api_key = "UV5FBJ81HUFIOE3R"  # ここに取得したAPIキーを入れる

# ForeignExchangeクラスを使ってAPI接続
fx = ForeignExchange(key=api_key)

# USD/JPYのリアルタイム為替レートを取得
data, _ = fx.get_currency_exchange_rate(from_currency="USD", to_currency="JPY")

# 結果を表示
print(data)

# 取得したデータをDataFrameに変換
df = pd.DataFrame([data])

# 必要なカラムのみ選択
df = df[["5. Exchange Rate", "6. Last Refreshed"]]

# カラム名を変更
df.columns = ["Exchange Rate", "Last Refreshed"]

# データを表示
print(df)

import time

while True:
    data, _ = fx.get_currency_exchange_rate(from_currency="USD", to_currency="JPY")
    exchange_rate = data["5. Exchange Rate"]
    timestamp = data["6. Last Refreshed"]

    print(f"Time: {timestamp}, USD/JPY: {exchange_rate}")

    time.sleep(60)  # 60秒ごとにデータを取得

from alpha_vantage.foreignexchange import ForeignExchange
import time
import os

# 環境変数からAPIキーを取得
api_key = os.getenv("ALPHA_VANTAGE_API_KEY")

fx = ForeignExchange(key=api_key)

while True:
    data, _ = fx.get_currency_exchange_rate(from_currency="USD", to_currency="JPY")
    exchange_rate = data["5. Exchange Rate"]
    timestamp = data["6. Last Refreshed"]

    print(f"Time: {timestamp}, USD/JPY: {exchange_rate}")

    time.sleep(60)  # 1分ごとに取得