# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iglQI0aw9oGTIzpjDjU7WYkUp09lgVeG
"""

import requests
import datetime

# APIキー（GitHub Actions用には後ほど環境変数として設定）
API_KEY = '574b870eec85d698cb4fb055'
url = f"https://v6.exchangerate-api.com/v6/{API_KEY}/latest/USD"

response = requests.get(url)
data = response.json()

# レートを取得
jpy_rate = data['conversion_rates']['JPY']
now = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')

# 分析処理の代わりにログ出力
print(f"[{now}] USD/JPY = {jpy_rate}")